/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

/**
 *
 * @author Wanda
 */

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication3.Configs.replaceLines;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class NewJFrame extends javax.swing.JFrame {    
    public String masterwal= null;
    public String slavewal=null;
    public String sentlsn= null;
    public String replaylsn=null;
    public String replaylsn2=null;
    Configs con = new Configs();
    Scanner listproduk = new Scanner(con.GetProp("produk"));
    private javax.swing.Timer autoTimer;
    private boolean timerRunning = false;    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        TableRowSorter<TableModel> sorter =
        new TableRowSorter<>(tableStatus.getModel());
        sorter.setComparator(5, (s1, s2) -> {
            int p1 = getPriority(s1.toString());
            int p2 = getPriority(s2.toString());
            return Integer.compare(p1, p2);
        });
        tableStatus.setRowSorter(sorter);
        sorter.toggleSortOrder(5);
        
        tableStatus.setDefaultRenderer(
            Object.class,
            new StatusColorRenderer()
            );
        
    System.out.println(System.getProperty("java.version"));
    System.out.println(System.getProperty("java.home"));        
        listproduk.useDelimiter(",");
        while (listproduk.hasNext())
        {            
            String templist = listproduk.next();            
            combo1.addItem(templist);
            String masterenc=templist+".master.enc";
            String masterpass=templist+".master.password";                        
            if (con.GetProp(masterenc).equals("0")){
                String newpass = con.enctext(con.GetProp(masterpass));
//                con.UpdateProp(masterpass, newpass);
//                con.UpdateProp(masterenc, "1");
                String masterpass1=masterpass+"="+con.GetProp(masterpass);
                String masterpass2=masterpass+"="+newpass;
                replaceLines(masterpass1,masterpass2);
                replaceLines(masterenc+"=0",masterenc+"=1");
            }                        
        }
    }

    private int getPriority(String status) {
        switch (status) {
            case "TIDAK SINKRON":
                return 1;
            case "SEDANG NGEJAR":
                return 2;
            case "SINKRON":
                return 3;
            default:
                return 1;
        }
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStatus = new javax.swing.JTable();
        cekall = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        combo1 = new javax.swing.JComboBox<>();
        clear2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        master1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slave1 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        cek = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lama_timer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timer = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("monitoring streaming replication postgresql 8.7");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        tableStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUK", "APPNAME", "CLIENTADDR", "SENTLSN", "REPLAYLSN", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tableStatus);

        cekall.setBackground(new java.awt.Color(255, 255, 0));
        cekall.setText("CEK ALL");
        cekall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekallActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 255, 204));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        combo1.setName("combo1"); // NOI18N
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        clear2.setBackground(new java.awt.Color(255, 255, 204));
        clear2.setText("CLEAR");
        clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ActionPerformed(evt);
            }
        });

        jLabel1.setText("master");

        master1.setText("wal master");

        jLabel3.setText("slave");

        slave1.setText("wal slave");

        status1.setBackground(new java.awt.Color(153, 204, 255));
        status1.setText("status");

        cek.setBackground(new java.awt.Color(255, 255, 0));
        cek.setText("CEK");
        cek.setName("cek"); // NOI18N
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(master1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addComponent(status1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clear2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(cek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clear2)
                        .addComponent(master1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slave1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Copyright@2026 wanda. All Rights Reserved");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        lama_timer.setText("30");

        jLabel4.setText("Timer (menit)");

        timer.setBackground(java.awt.Color.green);
        timer.setText("START");
        timer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AUTO REFRESH");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lama_timer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lama_timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jam.setText("waktu cek all");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cekall, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cekall, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("monitoring streaming replication postgresql 8.5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekallActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        jam.setText(sdf.format(new Date()));
        Scanner produk = new Scanner(con.GetProp("produk"));
        produk.useDelimiter(",");
        while (produk.hasNext())
        {            
            sentlsn="";
            replaylsn="";
            replaylsn2 = "";            
            String sentlsn2 = "";
            String status="";
            String temp = produk.next();
            String masterip=con.GetProp(temp+".master.ip");
            String masterport=con.GetProp(temp+".master.port");
            String masteruser=con.GetProp(temp+".master.user");
            String masterpass=con.dectext(con.GetProp(temp+".master.password"));
            String masterdb=con.GetProp(temp+".master.db");
            String clientaddr=con.GetProp(temp+".slave.ip");
            String appname=con.GetProp(temp+".slave.appname");               
            LsnData data1 = getlsn(masterip, masterport, masteruser,masterpass, masterdb, appname, clientaddr);
            status=data1.getStatus();
            if ("TIDAK SINKRON".equals(data1.getStatus()))
            {
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                LsnData data2 = getlsn(masterip, masterport, masteruser,masterpass, masterdb, appname, clientaddr);                
/*
                System.out.println("replaylsn:"+ data1.getReplayLsn());
                System.out.println("replaylsn2:"+ data2.getReplayLsn());
                System.out.println("status2:"+data2.getStatus());
                System.out.println("sentlsn:"+ data1.getSentLsn());
                System.out.println("sentlsn2:"+ data2.getSentLsn());                
*/
                if (!data1.getReplayLsn().equals(data2.getReplayLsn())) {
                    status = "SEDANG NGEJAR";
                } else {status="TIDAK SINKRON";}                               
            }            

            DefaultTableModel model = (DefaultTableModel) tableStatus.getModel();
            model.addRow(new Object[]{temp,appname,clientaddr,data1.getSentLsn(),data1.getReplayLsn(),status});
        }
    }//GEN-LAST:event_cekallActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableStatus.getModel();
        model.setRowCount(0);        
    }//GEN-LAST:event_clearActionPerformed

    private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ActionPerformed
        // TODO add your handling code here:
        master1.setText("wal master");
        slave1.setText("wal slave");
        status1.setText("status");        
    }//GEN-LAST:event_clear2ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        // TODO add your handling code here:
        sentlsn="";
        replaylsn="";
        String temp = combo1.getSelectedItem().toString();
            String masterip=con.GetProp(temp+".master.ip");
            String masterport=con.GetProp(temp+".master.port");
            String masteruser=con.GetProp(temp+".master.user");
            String masterpass=con.dectext(con.GetProp(temp+".master.password"));
            String masterdb=con.GetProp(temp+".master.db");
            String clientaddr=con.GetProp(temp+".slave.ip");
            String appname=con.GetProp(temp+".slave.appname");
            LsnData data1 = getlsn(masterip, masterport, masteruser,masterpass, masterdb, appname, clientaddr);
            master1.setText(data1.getSentLsn());
            slave1.setText(data1.getReplayLsn());
            status1.setText(temp+" "+data1.getStatus());
    }//GEN-LAST:event_cekActionPerformed

    private void timerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerActionPerformed
        // TODO add your handling code here:
        if (!timerRunning) {
            int interval = Integer.parseInt(lama_timer.getText()) * 60 * 1000;;
            timerRunning = true;           
            timer.setBackground(Color.RED);
            timer.setText("STOP");
            lama_timer.setEditable(false);
            clear.doClick();
            cekall.doClick();

            autoTimer = new javax.swing.Timer(interval, e -> {
                clear.doClick();
                cekall.doClick();
            });
            autoTimer.start();
        } else {
            timerRunning = false;
            if (autoTimer != null) {
                autoTimer.stop();
            }
            timer.setBackground(Color.GREEN);
            timer.setText("START");
            lama_timer.setEditable(true);
        }        
    }//GEN-LAST:event_timerActionPerformed

private LsnData getlsn(
        String masterip,
        String masterport,
        String masteruser,
        String masterpass,
        String masterdb,
        String appname,
        String clientaddr) {
    String jdbcURL1="jdbc:postgresql://"+masterip+":"+masterport+"/"+masterdb;
    String sent_lsn="";
    String replay_lsn="";
    LsnData data = new LsnData();

    try {
        Connection connection1= DriverManager.getConnection(jdbcURL1, masteruser,masterpass);
        String sql1 = "select sent_lsn,replay_lsn from pg_stat_replication "
           + "where application_name='"+appname+"'"
           + " and client_addr='"+clientaddr+"'";
        Statement statement1 = connection1.createStatement();
            
        ResultSet result1 = statement1.executeQuery(sql1);
        while (result1.next()) {
            sent_lsn = result1.getString("sent_lsn");
            replay_lsn = result1.getString("replay_lsn");
        }            

        data.setSentLsn(sent_lsn);
        data.setReplayLsn(replay_lsn);

        if (replay_lsn == null || replay_lsn.isEmpty()) {
            data.setStatus("TIDAK SINKRON");
        } else if (sent_lsn.equals(replay_lsn)) {
            data.setStatus("SINKRON");
        } else {
            data.setStatus("TIDAK SINKRON");
        }
        connection1.close();
        return data;            
    } catch (SQLException ex) {
        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        data.setSentLsn("");
        data.setReplayLsn("");
        data.setStatus("Koneksi gagal");
        return data;
    }       
}    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cek;
    private javax.swing.JButton cekall;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear2;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jam;
    private javax.swing.JTextField lama_timer;
    private javax.swing.JLabel master1;
    private javax.swing.JLabel slave1;
    private javax.swing.JLabel status1;
    private javax.swing.JTable tableStatus;
    private javax.swing.JToggleButton timer;
    // End of variables declaration//GEN-END:variables
}
