/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

/**
 *
 * @author Wanda
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication3.Configs.replaceLines;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

public class NewJFrame extends javax.swing.JFrame {    
    public String masterwal= null;
    public String slavewal=null;
    public String sentlsn= null;
    public String replaylsn=null;
    public String replaylsn2=null;
    Configs con = new Configs();
    Scanner listproduk = new Scanner(con.GetProp("produk"));    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        tableStatus.setDefaultRenderer(
            Object.class,
            new StatusColorRenderer()
            );
        
    System.out.println(System.getProperty("java.version"));
    System.out.println(System.getProperty("java.home"));        
        listproduk.useDelimiter(",");
        while (listproduk.hasNext())
        {            
            String templist = listproduk.next();            
            combo1.addItem(templist);
            String masterenc=templist+".master.enc";
            String masterpass=templist+".master.password";                        
            if (con.GetProp(masterenc).equals("0")){
                String newpass = con.enctext(con.GetProp(masterpass));
//                con.UpdateProp(masterpass, newpass);
//                con.UpdateProp(masterenc, "1");
                String masterpass1=masterpass+"="+con.GetProp(masterpass);
                String masterpass2=masterpass+"="+newpass;
                replaceLines(masterpass1,masterpass2);
                replaceLines(masterenc+"=0",masterenc+"=1");
            }                        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableStatus = new javax.swing.JTable();
        buttonRead = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        combo1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        master1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slave1 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        cek = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("monitoring streaming replication postgresql 8.5");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        tableStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUK", "APPNAME", "CLIENTADDR", "SENTLSN", "REPLAYLSN", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tableStatus);

        buttonRead.setBackground(new java.awt.Color(255, 255, 0));
        buttonRead.setText("CEK ALL");
        buttonRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReadActionPerformed(evt);
            }
        });

        buttonSave.setBackground(new java.awt.Color(255, 255, 204));
        buttonSave.setText("CLEAR");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));

        combo1.setName("combo1"); // NOI18N
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("master");

        master1.setText("wal master");

        jLabel3.setText("slave");

        slave1.setText("wal slave");

        status1.setBackground(new java.awt.Color(153, 204, 255));
        status1.setText("status");

        cek.setBackground(new java.awt.Color(255, 255, 0));
        cek.setText("CEK");
        cek.setName("cek"); // NOI18N
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(master1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(slave1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addComponent(status1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(cek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(master1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slave1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel2.setText("Copyright@2026 wanda. All Rights Reserved");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(buttonRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRead, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(164, 164, 164)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("monitoring streaming replication postgresql 8.5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReadActionPerformed
        // TODO add your handling code here:
        Scanner produk = new Scanner(con.GetProp("produk"));
        produk.useDelimiter(",");
        while (produk.hasNext())
        {            
            sentlsn="";
            replaylsn="";
            replaylsn2 = "";            
            String sentlsn2 = "";
            String status="";
            String temp = produk.next();
            String masterip=con.GetProp(temp+".master.ip");
            String masterport=con.GetProp(temp+".master.port");
            String masteruser=con.GetProp(temp+".master.user");
            String masterpass=con.dectext(con.GetProp(temp+".master.password"));
            String masterdb=con.GetProp(temp+".master.db");
            String clientaddr=con.GetProp(temp+".slave.ip");
            String appname=con.GetProp(temp+".slave.appname");               
            LsnData data1 = getlsn(masterip, masterport, masteruser,masterpass, masterdb, appname, clientaddr);
            status=data1.getStatus();
            if ("TIDAK SINKRON".equals(data1.getStatus()))
            {
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                LsnData data2 = getlsn(masterip, masterport, masteruser,masterpass, masterdb, appname, clientaddr);                
/*
                System.out.println("replaylsn:"+ data1.getReplayLsn());
                System.out.println("replaylsn2:"+ data2.getReplayLsn());
                System.out.println("status2:"+data2.getStatus());
                System.out.println("sentlsn:"+ data1.getSentLsn());
                System.out.println("sentlsn2:"+ data2.getSentLsn());                
*/
                if (!data1.getReplayLsn().equals(data2.getReplayLsn())) {
                    status = "SEDANG NGEJAR";
                } else {status="TIDAK SINKRON";}                               
            }            

            DefaultTableModel model = (DefaultTableModel) tableStatus.getModel();
            model.addRow(new Object[]{temp,appname,clientaddr,data1.getSentLsn(),data1.getReplayLsn(),status});
        }                
    }//GEN-LAST:event_buttonReadActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableStatus.getModel();
        model.setRowCount(0);        
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        master1.setText("wal master");
        slave1.setText("wal slave");
        status1.setText("status");        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        // TODO add your handling code here:
        sentlsn="";
        replaylsn="";
        String temp = combo1.getSelectedItem().toString();
            String masterip=con.GetProp(temp+".master.ip");
            String masterport=con.GetProp(temp+".master.port");
            String masteruser=con.GetProp(temp+".master.user");
            String masterpass=con.dectext(con.GetProp(temp+".master.password"));
            String masterdb=con.GetProp(temp+".master.db");
            String clientaddr=con.GetProp(temp+".slave.ip");
            String appname=con.GetProp(temp+".slave.appname");
            LsnData data1 = getlsn(masterip, masterport, masteruser,masterpass, masterdb, appname, clientaddr);
            master1.setText(data1.getSentLsn());
            slave1.setText(data1.getReplayLsn());
            status1.setText(temp+" "+data1.getStatus());
    }//GEN-LAST:event_cekActionPerformed

private LsnData getlsn(
        String masterip,
        String masterport,
        String masteruser,
        String masterpass,
        String masterdb,
        String appname,
        String clientaddr) {
    String jdbcURL1="jdbc:postgresql://"+masterip+":"+masterport+"/"+masterdb;
    String sent_lsn="";
    String replay_lsn="";
    LsnData data = new LsnData();

    try {
        Connection connection1= DriverManager.getConnection(jdbcURL1, masteruser,masterpass);
        String sql1 = "select sent_lsn,replay_lsn from pg_stat_replication "
           + "where application_name='"+appname+"'"
           + " and client_addr='"+clientaddr+"'";
        Statement statement1 = connection1.createStatement();
            
        ResultSet result1 = statement1.executeQuery(sql1);
        while (result1.next()) {
            sent_lsn = result1.getString("sent_lsn");
            replay_lsn = result1.getString("replay_lsn");
        }            

        data.setSentLsn(sent_lsn);
        data.setReplayLsn(replay_lsn);

        if (replay_lsn == null || replay_lsn.isEmpty()) {
            data.setStatus("TIDAK SINKRON");
        } else if (sent_lsn.equals(replay_lsn)) {
            data.setStatus("SINKRON");
        } else {
            data.setStatus("TIDAK SINKRON");
        }
        connection1.close();
        return data;            
    } catch (SQLException ex) {
        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        data.setSentLsn("");
        data.setReplayLsn("");
        data.setStatus("Koneksi gagal");
        return data;
    }       
}    
/*    
    private String getlsn(String masterip, String masterport, String masteruser, String masterpass, String masterdb
    ,String appname, String clientaddr, String sentlsn, String replaylsn){
        String jdbcURL1="jdbc:postgresql://"+masterip+":"+masterport+"/"+masterdb;
        String masterusername = masteruser;
        String masterpassword = masterpass;
        String sent_lsn = "";
        String replay_lsn = "";
        String hasil;
        try {
            Connection connection1= DriverManager.getConnection(jdbcURL1, masterusername,masterpassword);
            String sql1 = "select sent_lsn,replay_lsn from pg_stat_replication "
                    + "where application_name='"+appname+"'"
                    + "and client_addr='"+clientaddr+"'";
            Statement statement1 = connection1.createStatement();
            
            ResultSet result1 = statement1.executeQuery(sql1);
            while (result1.next()) {
                sent_lsn = result1.getString("sent_lsn");
                replay_lsn = result1.getString("replay_lsn");
            }            

            sentlsn = sent_lsn;
            replaylsn = replay_lsn;
            this.sentlsn=sentlsn;
            this.replaylsn=replaylsn;
            if (replaylsn.isEmpty()) 
            {hasil="TIDAK SINKRON";}
            else if (sentlsn.equals(replaylsn)) 
            {hasil="SINKRON";}
            else {hasil="TIDAK SINKRON";}
                
            connection1.close();
            return hasil;
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            return "Koneksi gagal";
        }        
    }
*/    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRead;
    private javax.swing.JButton buttonSave;
    private javax.swing.JButton cek;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel master1;
    private javax.swing.JLabel slave1;
    private javax.swing.JLabel status1;
    private javax.swing.JTable tableStatus;
    // End of variables declaration//GEN-END:variables
}
